Greetings human.

I regret to inform you that your background process has failed.

An exception of class <%= @e.class.to_s %> occurred.

The exception message was:

  <%= @e.message %>

The backtrace:

<%= @e.backtrace.join("\n") %>

Have a nice day!

-- 
FabIO

“Don’t worry if it doesn’t work right.  If everything did, you’d be out of a job.”
  -- Mosher’s Law of Software Engineering